# Generated by Django 4.0.4 on 2022-08-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audis', '0002_choicequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='question_response',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('Tech', 'Tech'), ('Both Core and Tech', 'Both Core and Tech')], max_length=100, null=True),
        ),
    ]
