# Generated by Django 4.0.4 on 2022-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audis', '0003_alter_choicequestion_question_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='question_response',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
